module.exports = {
  reactStrictMode: true,
  env: {
    WEBSITE_URL: process.env.WEBSITE_URL,
    WEBSITE_EMAIL: process.env.WEBSITE_EMAIL,
    WEBSITE_ADDRESS_NAME: process.env.WEBSITE_ADDRESS_NAME,
    WEBSITE_ADDRESS_STREET: process.env.WEBSITE_ADDRESS_STREET,
    WEBSITE_ADDRESS_CITY: process.env.WEBSITE_ADDRESS_CITY,
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID
  }
}
