export const lang = {
    "en": {
        "about": "About and Privacy",
        "aboutBackToHomepage": "back to homepage",
        "addLocationButtonText": "Add Nude Place",
        "addLocationFormValidateAddress": "Please drag the marker to the position of the nude place and fetch the address.",
        "addLocationFormValidateTitleRequired": "Title required.",
        "addLocationFormValidateTitleLength": "Title should be 100 characters or less.",
        "addLocationFormValidateTypeRequired": "Type required.",
        "addLocationFormValidateDescriptionLength": "Description should be 1000 characters or less.",
        "addLocationFormValidateUrlInvalid": "The website url is invalid.",
        "addLocationFormPositionInfo": "Drag the blue marker to the nude place on the map. Please try to find the exact position.",
        "addLocationFormIsAddressCorrect": "Is the address correct? If not, please take a look at the map and move the blue marker to the exact position.",
        "addLocationFormAddressLabel": "Address",
        "addLocationFormTitleLabel": "Title",
        "addLocationFormTitlePlaceholder": "Name of the lake, beach section, ...",
        "addLocationFormTypeLabel": "Type",
        "addLocationFormDescriptionLabel": "Description",
        "addLocationFormDescriptionPlaceholder": "Directions, opening hours, entrance fees, ...",
        "addLocationFormUrlLabel": "Website",
        "addLocationFormUrlPlaceholder": "https://...",
        "addLocationFormSubmit": "Submit Nude Place",
        "addLocationTitle": "Add Nude Place",
        "addLocationSuccessText": "Thank you for submitting a nude place! Your submission will be checked by our moderators before getting published. Please allow 1-2 days for it to show up on the website.",
        "addLocationSuccessButton": "Add Another Nude Place",
        "continent_europe": "Europe",
        "continent_other": "Other Countries",
        "copyUrlToClipboard": "Copy URL to Clipboard",
        "copiedUrlToClipboard": "Copied!",
        "countries": "Countries",
        "countryShowingLocationsCount": "Showing",
        "countryName_AR": "Argentina",
        "countryName_AU": "Australia",
        "countryName_AT": "Austria",
        "countryName_BE": "Belgium",
        "countryName_BR": "Brazil",
        "countryName_BG": "Bulgaria",
        "countryName_CA": "Canada",
        "countryName_CR": "Costa Rica",
        "countryName_HR": "Croatia",
        "countryName_CY": "Cyprus",
        "countryName_CZ": "Czech Republic",
        "countryName_DK": "Denmark",
        "countryName_EE": "Estonia",
        "countryName_FI": "Finland",
        "countryName_FR": "France",
        "countryName_DE": "Germany",
        "countryName_GR": "Greece",
        "countryName_HU": "Hungary",
        "countryName_IS": "Iceland",
        "countryName_ID": "Indonesia",
        "countryName_IE": "Ireland",
        "countryName_IT": "Italy",
        "countryName_JM": "Jamaica",
        "countryName_JP": "Japan",
        "countryName_LV": "Latvia",
        "countryName_LT": "Lithuania",
        "countryName_LU": "Luxembourg",
        "countryName_MX": "Mexico",
        "countryName_ME": "Montenegro",
        "countryName_NL": "Netherlands",
        "countryName_NZ": "New Zealand",
        "countryName_NO": "Norway",
        "countryName_PL": "Poland",
        "countryName_PT": "Portugal",
        "countryName_PR": "Puerto Rico",
        "countryName_RO": "Romania",
        "countryName_RU": "Russian Federation",
        "countryName_RS": "Serbia",
        "countryName_SK": "Slovakia",
        "countryName_SI": "Slovenia",
        "countryName_ZA": "South Africa",
        "countryName_ES": "Spain",
        "countryName_SE": "Sweden",
        "countryName_CH": "Switzerland",
        "countryName_TH": "Thailand",
        "countryName_TR": "Turkey",
        "countryName_UA": "Ukraine",
        "countryName_GB": "United Kingdom",
        "countryName_US": "United States",
        "countryName_VN": "Vietnam",
        "countryNudePlace": "nude place",
        "countryNudePlaces": "nude places",
        "countryNoLocationsFound": "No nude places found in this area. Zoom out of the map or remove filters to see more.",
        "countrySelectLabel": "Country",
        "countrySelectPlaceholder": "Show nude places in...",
        "externalLinkWarningText": "You are about to leave this website. We are not responsible for the content of any linked external website. Please note that these websites' privacy policies and security practices may differ from this website's standards. Do you wish to continue?",
        "fetchAddress": "Fetch Address",
        "fetchedAddress": "Address fetched!",
        "formErrorsWarning": "An error occurred when submitting the form. Please check your input and try again.",
        "locationInfoListLabel": "Location Info",
        "locationInfoListShowOnMap": "Show on Map",
        "locationInfoListWebsite": "Website",
        "locationInfoListLastUpdated": "Last updated",
        "locationReviewLabel_accessible": "The place is easy to access.",
        "locationReviewLabel_clean": "The place is nice and clean.",
        "locationReviewLabel_friendly": "People are nice and nudist-friendly.",
        "locationReviewLabel_safe": "The place is safe for everybody to be here.",
        "locationReviewTitle": "Review Nude Place",
        "locationReviewSubtitle": "Tell us what you like about this place.",
        "locationReviewSubmit": "Submit review",
        "locationTypeFilter_beach": "Beach",
        "locationTypeFilter_sauna": "Sauna & Thermal Bath",
        "locationTypeFilter_resort": "Resort",
        "locationTypeFilter_camp_site": "Camp Site",
        "locationTypeFilter_club": "Club",
        "locationTypeFilter_accommodation": "Accommodation",
        "locationTypeFilter_hot_spring": "Hot Spring",
        "locationTypeFilter_pool": "Pool",
        "locationTypeFilter_walking": "Walking",
        "locationTypeFilter_tan_only": "Tan Only",
        "locationTypeFilter_no_nudism_anymore": "No Nudism Anymore",
        "locationTypeFilter_legacy": "Legacy",
        "locationTypeFilter__undefined_": "Undefined",
        "readMore": "Read more",
        "reportLocationButtonText": "Report As Inappropriate",
        "reportLocationMailSubject": "Report Location:",
        "reportLocationMailPrivacy": "By sending this email, you agree that the data you provide is processed in order to solve the issue. All personal data will be deleted after the issue was solved.",
        "reportLocationMailText": "Please specify the issue below:",
        "locationInfoDisclaimer": "Please note that we cannot guarantee the information to be correct and up-to-date. Make sure to confirm it before planning your trip. You can help us by reporting any incorrect or outdated information.",
        "404pageTitle": "404 - Page Not Found",
        "404pageText": "The page you requested does not exist. Please go back to the start page.",
        "500pageTitle": "500 - Internal Server Error",
        "500pageText": "An error occurred when processing your request. Please try again later.",
    },
    "de": {
        "about": "Impressum und Datenschutzerklärung",
        "aboutBackToHomepage": "zurück zur Startseite",
        "addLocationButtonText": "Ort hinzufügen",
        "addLocationFormValidateAddress": "Bitte ziehe den Marker an die Position des nackten Ortes auf der Karte und lasse die Adresse ermitteln.",
        "addLocationFormValidateTitleRequired": "Du musst einen Titel angeben.",
        "addLocationFormValidateTitleLength": "Der Titel darf maximal 100 Zeichen lang sein.",
        "addLocationFormValidateTypeRequired": "Du musst einen Typ auswählen.",
        "addLocationFormValidateDescriptionLength": "Die Beschreibung darf maximal 1000 Zeichen lang sein.",
        "addLocationFormValidateUrlInvalid": "Die eingegebene URL der Webseite ist ungültig.",
        "addLocationFormPositionInfo": "Ziehe den blauen Marker an die Position des nackten Ortes auf der Karte. Versuche bitte, den Ort möglichst genau zu markieren.",
        "addLocationFormIsAddressCorrect": "Ist die Adresse korrekt? Falls nicht, schaue bitte auf die Karte und ziehe den blauen Marker auf die exakte Position.",
        "addLocationFormAddressLabel": "Adresse",
        "addLocationFormTitleLabel": "Titel",
        "addLocationFormTitlePlaceholder": "Name des Sees, Strandabschnitt, ...",
        "addLocationFormTypeLabel": "Typ",
        "addLocationFormDescriptionLabel": "Beschreibung",
        "addLocationFormDescriptionPlaceholder": "Wegweiser, Öffnungszeiten, Eintrittspreise, ...",
        "addLocationFormUrlLabel": "Webseite",
        "addLocationFormUrlPlaceholder": "https://...",
        "addLocationFormSubmit": "Nackten Ort einreichen",
        "addLocationFormErrorsWarning": "Beim Absenden des Formulars ist ein Fehler aufgetreten. Bitte überprüfe deine Eingaben und versuche es erneut.",
        "addLocationTitle": "Nackten Ort hinzufügen",
        "addLocationSuccessText": "Vielen Dank! Dein Vorschlag wird von unseren Moderatoren geprüft und erscheint innerhalb von 1-2 Tagen auf der Webseite.",
        "addLocationSuccessButton": "Einen weiteren Ort einreichen",
        "continent_europe": "Europa",
        "continent_other": "Weitere Länder",
        "copyUrlToClipboard": "Link-Adresse kopieren",
        "copiedUrlToClipboard": "Kopiert!",
        "countries": "Länder",
        "countryShowingLocationsCount": "Zeige",
        "countryName_AR": "Argentinien",
        "countryName_AU": "Australien",
        "countryName_AT": "Österreich",
        "countryName_BE": "Belgien",
        "countryName_BR": "Brasilien",
        "countryName_BG": "Bulgarien",
        "countryName_CA": "Kanada",
        "countryName_CR": "Costa Rica",
        "countryName_HR": "Kroatien",
        "countryName_CY": "Zypern",
        "countryName_CZ": "Tschechische Republik",
        "countryName_DK": "Dänemark",
        "countryName_EE": "Estland",
        "countryName_FI": "Finnland",
        "countryName_FR": "Frankreich",
        "countryName_DE": "Deutschland",
        "countryName_GR": "Griechenland",
        "countryName_HU": "Ungarn",
        "countryName_IS": "Island",
        "countryName_ID": "Indonesien",
        "countryName_IE": "Irland",
        "countryName_IT": "Italien",
        "countryName_JM": "Jamaika",
        "countryName_JP": "Japan",
        "countryName_LV": "Lettland",
        "countryName_LT": "Litauen",
        "countryName_LU": "Luxemburg",
        "countryName_MX": "Mexiko",
        "countryName_ME": "Montenegro",
        "countryName_NL": "Niederlande",
        "countryName_NZ": "Neuseeland",
        "countryName_NO": "Norwegen",
        "countryName_PL": "Polen",
        "countryName_PT": "Portugal",
        "countryName_PR": "Puerto Rico",
        "countryName_RO": "Rumänien",
        "countryName_RU": "Russland",
        "countryName_RS": "Serbien",
        "countryName_SK": "Slowakei",
        "countryName_SI": "Slowenien",
        "countryName_ZA": "Südafrika",
        "countryName_ES": "Spanien",
        "countryName_SE": "Schweden",
        "countryName_CH": "Schweiz",
        "countryName_TH": "Thailand",
        "countryName_TR": "Türkei",
        "countryName_UA": "Ukraine",
        "countryName_GB": "Vereinigtes Königreich",
        "countryName_US": "Vereinigte Staaten",
        "countryName_VN": "Vietnam",
        "countryNudePlace": "nackten Ort",
        "countryNudePlaces": "nackte Orte",
        "countryNoLocationsFound": "Keine nackten Orte gefunden. Bitte zoome aus der Karte heraus oder entferne aktive Filter.",
        "countrySelectLabel": "Land",
        "countrySelectPlaceholder": "Zeige nackte Orte in...",
        "externalLinkWarningText": "Dieser Link führt zu einer externen Webseite. Wir sind nicht verantwortlich für deren Inhalt. Es können andere Standards zu Sicherheit und Datenschutz gelten. Trotzdem fortfahren?",
        "fetchAddress": "Adresse ermitteln",
        "fetchedAddress": "Adresse ermittelt!",
        "formErrorsWarning": "Beim Senden des Formulars ist ein Fehler aufgetreten. Prüfe bitte deine Eingaben und versuche es nochmal",
        "locationInfoListLabel": "Orts-Informationen",
        "locationInfoListShowOnMap": "Auf einer Karte zeigen",
        "locationInfoListWebsite": "Webseite",
        "locationInfoListLastUpdated": "Zuletzt aktualisiert",
        "locationReviewLabel_accessible": "Der Ort ist gut zu erreichen.",
        "locationReviewLabel_clean": "Der Ort ist schön und sauber.",
        "locationReviewLabel_friendly": "Die Leute sind nett und tolerant gegenüber FKK.",
        "locationReviewLabel_safe": "Der Ort ist sicher für alle Besucher.",
        "locationReviewTitle": "Nackten Ort bewerten",
        "locationReviewSubtitle": "Was gefällt dir an diesem Ort besonders?",
        "locationReviewSubmit": "Bewertung absenden",
        "locationTypeFilter_beach": "Strand",
        "locationTypeFilter_sauna": "Sauna & Therme",
        "locationTypeFilter_resort": "Resort",
        "locationTypeFilter_camp_site": "Camping",
        "locationTypeFilter_club": "Verein",
        "locationTypeFilter_accommodation": "Unterkunft",
        "locationTypeFilter_hot_spring": "Heiße Quelle",
        "locationTypeFilter_pool": "Schwimmbad",
        "locationTypeFilter_walking": "Wandern",
        "locationTypeFilter_tan_only": "Sonnenbaden",
        "locationTypeFilter_no_nudism_anymore": "Kein FKK mehr",
        "locationTypeFilter_legacy": "Legacy",
        "locationTypeFilter__undefined_": "Undefined",
        "readMore": "Weiterlesen",
        "reportLocationButtonText": "Unangemessenen Ort melden",
        "reportLocationMailSubject": "Einen Ort melden:",
        "reportLocationMailPrivacy": "Wenn du diese E-Mail sendest, stimmst du der Verarbeitung der angegebenen Daten zur Bearbeitung der Meldung zu. Alle persönlichen Daten werden nach Abschluss der Bearbeitung gelöscht.",
        "reportLocationMailText": "Gib hier bitte den Grund für deine Meldung an:",
        "locationInfoDisclaimer": "Wir können die Richtigkeit und Aktualität dieser Informationen nicht garantieren. Plane deinen Ausflug daher sorgfältig. Du kannst uns helfen, indem du uns Hinweise zu falschen und veralteten Informationen gibst.",
        "404pageTitle": "404 - Seite nicht gefunden",
        "404pageText": "Die angeforderte Seite existiert nicht. Bitte kehre zur Startseite zurück",
        "500pageTitle": "500 - Internal Server Error",
        "500pageText": "Bei der Verarbeitung deiner Anfrage ist ein Fehler aufgetreten. Versuche es bitte später erneut.",
    }

}