import Head from 'next/head';
import Link from 'next/link';
import LinkList from '../components/LinkList';
import Layout from '../components/Layout';
import initFirebase from '../lib/firebase';

export default function Home({ countries }) {
  const mapData = {
    mapPosition: [
      51.165691, 10.451526
    ],
    markerPositions: buildCountryMarkerPositions(countries),
    zoom: 3,
  }

  return (
    <div>
      <Head>
        <title>{getTitleString()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout mapData={mapData}>
        <h1>
          Nude Places
        </h1>
        <LinkList listItems={getCountryListItems(countries)} />
      </Layout>
    </div>
  )
}

export async function getStaticProps() {

  let db = await initFirebase()
  let data = db.collection('countries').get().then((snapshot) => {
    return snapshot.docs.map(doc => doc.data())
  })
    .catch((error) => {
      console.log("Error getting documents: ", error);
    });

  const countries = await data

  return {
    props: {
      countries: countries ?? {}
    }
  }
}



function getTitleString() {
  const titleString = [];
  titleString.push(`Nudist, Naturist, Clothing Optional Places and Beaches worldwide`);
  titleString.push("nudeplaces");
  return titleString.join(" – ")
}



function buildCountryMarkerPositions(countries) {
  const markerPositions = [];

  countries.map((country) => {
    markerPositions.push({
      latitude: country.latitude,
      longitude: country.longitude,
      title: country.name,
      url: buildCountryUrl(country)
    })
  })

  return markerPositions;
}


function buildCountryUrl(country) {
  return `/${encodeURIComponent(country.urlName)}`;
}



function getCountryListItems(countries) {
  const listItems = [];

  countries.map((country) => {
    listItems.push({
      href: buildCountryUrl(country),
      text: country.name,
    })
  })

  return listItems;
}
