import Head from 'next/head'
import styles from '../styles/Home.module.css'
import initFirebase from '../lib/firebase';

export default function Home({ countries }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {countries.map((country) => (
          <span key={country.id}>{country.isoCode}</span>
        ))}
      </main>
    </div>
  )
}

export async function getStaticProps() {

  let db = await initFirebase()
  let data = db.collection('countries').get().then((snapshot) => {
    return snapshot.docs.map(doc => doc.data())
  })
    .catch((error) => {
      console.log("Error getting documents: ", error);
    });

  const countries = await data

  return {
    props: {
      countries: countries ?? {}
    }
  }
}
